### ISSUE TITLE
Live demo on ios not working

### ISSUE THREAD

**Issue by lucasverra** [koddr/a2hs.js#4]
## Overview of the problem

I was trying to live demo on my upgraded iOS device, and I cannot see the banner

## Screenshots

![BE4B9613-C19D-46BE-9507-4FDDE10B5E1E](https://user-images.githubusercontent.com/11323803/73135352-5ae17b80-4041-11ea-86d9-aa6f4975c01b.png)

## Steps to Reproduce

1. Ios devise in private mode
2. Url specified for live demo 
3. Go

## Configuration

- Browser: safari
- OS/Device: IOS 13 latest version
- a2hs.js: do not know

**Comment by koddr** [comment]
@lucasverra hi! 🤝 

Thanks for report, fix it ASAP.

**Comment by koddr** [comment]
Fix it now (finally) 🥳
