### ISSUE TITLE
Add to IONIC/VUE PWA

### ISSUE THREAD

**Issue by damianlluch** [koddr/a2hs.js#6]
## Overview of the problem
Hi, thanks for sharing this resources.

In my App, I'm import this library modified for my project, and not work,I think the reason is the lack of the return method
You can modifying this project for PWA?
thanks!
## Screenshots

I have thus modified the library to be able to import

const AddToHomeScreen = function(settings = {}) {
....
....
....
...
....
export default AddToHomeScreen;

## Steps to Reproduce

1.
2.
3.

## Configuration

- Browser: 
- OS/Device: 
- a2hs.js:

**Comment by koddr** [comment]
Not sure to understand, what you mean?

**Comment by damianlluch** [comment]
Hi, is it necessary to have the manifest.json? because it is showing me the button but it is not installing the icon on the device.
On the other hand, does this not work for Android?

thanks!

**Comment by koddr** [comment]
@damianlluch it's only for iOS devices, because Android have built-in functions for it.

See demo for iOS: https://github.com/koddr/a2hs.js#demo

**Comment by damianlluch** [comment]
And is it necessary to have the manifest.son? I see your demo but not work in emulator.

**Comment by damianlluch** [comment]
It only shows the toast but when I click on it nothing happens.

![Uploading image (3).png…]()

**Comment by damianlluch** [comment]
![image](https://user-images.githubusercontent.com/1463804/78568406-5ba54380-7822-11ea-8be3-d26915a1a8a7.png)

**Comment by koddr** [comment]
That's right, it's only banner with help instructions. 

As you can see on it, you need to do manually things to add your PWA to Home screen on your iOS device.

**Comment by damianlluch** [comment]
ok, so this library only performs the function of displaying the toast?

**Comment by koddr** [comment]
Yep, this is just helper for install PWA on iOS.

**Comment by damianlluch** [comment]
Hello, so what is missing? I came up with this problem a few days ago. Safari does not accept this button as investigated, and the manifest would not work. So how do you achieve this functionality in iOs?

**Comment by koddr** [comment]
`a2h.js` doesn't _achieve_ any functions, it's only helper to manually added PWA to Home Screen.

**Comment by koddr** [comment]
Close issue, but feel free to open again 😉
